config/routes.rb
SampleApp::Application.routes.draw do
  devise_for :users
  resources :users#, only: [:show]
  resources :questions do
      resources :answers, only: [:create, :update, :destroy]
  end

  root to: 'questions#index'

  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/questions/upvote/:id', to: 'questions#upvote', as: :upvote_question
  match '/questions/downvote/:id', to: 'questions#downvote', as: :downvote_question
  match '/questions/clearvote/:id', to: 'questions#clearvote', as: :clearvote_question

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :title, :score
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voters, class_name: 'User', through: :votes, source: :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 10 }, uniqueness: true
  default_scope order: 'questions.score DESC'
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_filter :authenticate_user!, only: [:create, :destroy, :update, :upvote, :downvote, :clearvote]

    def index
        @questions = Question.paginate(page: params[:page])
    end

    def show
        @question = Question.find(params[:id])
        if user_signed_in?
          @user_vote = Vote.find_by_question_id_and_user_id(params[:id], current_user.id)
          @upvote_link = upvote_question_path
          @downvote_link = downvote_question_path
          @upvote_style = ""
          @downvote_style = ""
          if @user_vote
            if @user_vote.up?
              @upvote_link = clearvote_question_path
              @upvote_style = "background-color: green;"
            else
              @downvote_link = clearvote_question_path
              @downvote_style = "background-color: red;"
            end
          end
        end
    end

    def edit
        @question = Question.find(params[:id])
    end
    
    def upvote
      vote(1)
    end

    def downvote
      vote(2)
    end

    def clearvote
          @previous_vote = Vote.find_by_question_id_and_user_id(params[:id], current_user.id)
          if @previous_vote
            @previous_vote.destroy
          end
          redirect_to :back, notice: "Your vote is removed!"
    end

    def new
        @question = Question.new
    end

    def create
        @question = Question.new(params[:question])
        @question.user = current_user
        if @question.save
            redirect_to @question, notice: "Asked question successfully!"
        else
            render :new
        end
    end

    def update
        @question = Question.find(params[:id])
        if params[:question][:user_id] #Trying to update other's id
            redirect_to @question, alert: "You are not authorized to edit!"
        end
        if @question.update_attributes(params[:question])
            redirect_to @question, notice: "Question updated successfully!"
        else
            render :edit
        end
    end

    def destroy
        @question = Question.find(params[:id])
        if current_user == @question.user
            @question.destroy
            redirect_to root_path, notice: "Question deleted successfully"
        else
            redirect_to @question, alert: "You are not authorized to delete!"
        end
    end

    private
    def vote(value)
        @question = Question.find(params[:id])
        if @question.user == current_user
          redirect_to :back, alert: "You cannot vote your own question!"
        else
          @previous_vote = Vote.find_by_question_id_and_user_id(params[:id], current_user.id)
          if @previous_vote
            @previous_vote.destroy
            vote(value)
          else
              vote = Vote.new
              vote.question = @question
              vote.user = current_user
              vote.value = value
              if vote.save
                redirect_to :back, notice: "Your vote is recorded!"
              else
                redirect_to :back, alert: "Failed to record vote!"
              end
          end
        end
    end

end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, placeholder: "Type your Question here", id: "question_title_text_box" %>
    </div>
    <br />
    <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, rows: 5, placeholder: "Optional: Add more details about your question here", id: "question_details_textarea" %>
    </div>
    <div class="actions">
        <%= f.submit "Ask" %>
    </div>
<% end %>

app/views/questions/_question.html.erb
<li>
<span class="content">[<%= question.score.to_i %>] <%= link_to question.title, question %></span>
  <span class="timestamp">
    Asked <%= time_ago_in_words(question.created_at) %> ago <% if defined? skip_user%><% else %> by <%= link_to question.user.name, question.user %> <% end %>
  </span>
</li>

app/views/questions/edit.html.erb
<% provide(:title, "Edit Question") %>
<%= render partial: 'form' %>

app/views/questions/index.html.erb
<% provide(:title, 'All Questions') %>
<div class="span8">
    <ul class="questions">
        <%= render @questions %>
    </ul>
<%= will_paginate @questions %>
</div>

app/views/questions/new.html.erb
<% provide(:title, "Ask a new Question") %>
<%= render partial: 'form' %>

app/views/questions/show.html.erb
<% provide(:title, "Question") %>
<h3><big>[<%= @question.score %>] <em>Question</em>: <%= @question.title %></big></h3>
<hr />
<table class="fw">
  <tbody>
    <tr>
      <td><p class="lead text-justify"><%= markdown(@question.content) %></p></td>
    </tr>
    <tr>
        <td >
          <ul class="list-inline">
      <% if user_signed_in? %>
        <li><%= link_to "upvote", @upvote_link, style: @upvote_style %></li>
        <li><%= link_to "downvote", @downvote_link, style: @downvote_style %></li>
      <% end %>
      <% if current_user == @question.user %>
            <li><%= link_to "edit", edit_question_path %></li>
            <li><%= link_to "delete", question_path, method: :delete %></li>
      <% end %>
          </ul>
        </td>
      <td style="float:right"> 
        <%= gravatar_for @question.user %><br />
        Asked <%= time_ago_in_words(@question.created_at) %> ago by <%= link_to @question.user.name, @question.user %> </td>
    </tr>
    <tr>
    </tr>
  </tbody>
</table>
<% if user_signed_in? %>
<%= form_for([@question, @question.answers.build]) do |f| %>
  <div class="field">
    <h3>Answer</h3>
    <%= f.text_area :body, rows: "5", placeholder: "Type your answer here", id: "answer_box" %>
  </div>
  <div class="actions">
    <%= f.submit "Add Answer" %>
  </div>
<% end %>
<% end %>
  <h3>Answers (<%= @question.answers.count %>)</h3>
<% if @question.answers.count != 0 %>
  <ul class="answers">
    <%= render @question.answers %> 
  </ul>
  <!--  will_paginate @questions -->
<% end %>