config/routes.rb
SampleApp::Application.routes.draw do
  devise_for :users
  resources :users#, only: [:show]
  resources :questions do
      resources :answers, only: [:create, :update, :destroy]
  end

  root to: 'questions#index'

  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/questions/upvote/:id', to: 'questions#upvote', as: :upvote_question
  match '/questions/downvote/:id', to: 'questions#downvote', as: :downvote_question
  match '/questions/clearvote/:id', to: 'questions#clearvote', as: :clearvote_question

end

app/views/layouts/_footer.html.erb
<div class="footer" >
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Ask Rails", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Help",  help_path  %></li>
          <li><%= link_to "Users", users_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Ask!", new_question_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li> <%= link_to "Sign out", destroy_user_session_path, method: "delete" %> </li>
              </ul>
            </li>
          <% else %>
              <li><%= link_to "Sign in", new_user_session_path  %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content"width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

    </div>
    <%= render 'layouts/footer' %>
    <div style="height:25px">
    </div>
    <div style="diplay:block;">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>